/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Arsene' at '27/11/16 17:54' with Gradle 3.0
 *
 * @author Arsene, @date 27/11/16 17:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
